import type { DbCategory } from "./types";

export const BUILT_IN_CATEGORIES: DbCategory[] = [
  {
    id: "calendar_past",
    display_name: "Past calendar invites",
    description: "Calendar notifications whose event date has passed",
    priority: 1,
    default_action: "trash",
    enabled: 1,
  },
  {
    id: "automated_alerts",
    display_name: "Automated alerts",
    description: "CI/CD, monitoring, and system notification emails older than 30 days",
    priority: 2,
    default_action: "trash",
    enabled: 1,
  },
  {
    id: "social",
    display_name: "Social notifications",
    description: "LinkedIn, Facebook, Twitter/X, Instagram, Reddit, and similar",
    priority: 3,
    default_action: "trash",
    enabled: 1,
  },
  {
    id: "receipts",
    display_name: "Transactional receipts",
    description: "Order confirmations and receipts older than 6 months",
    priority: 4,
    default_action: "trash",
    enabled: 1,
  },
  {
    id: "promos",
    display_name: "Promotions & discounts",
    description: "Sale, coupon, and discount emails (likely expired)",
    priority: 5,
    default_action: "trash",
    enabled: 1,
  },
  {
    id: "newsletters",
    display_name: "Newsletters & marketing",
    description: "Mailing-list emails from senders you've never replied to",
    priority: 6,
    default_action: "trash",
    enabled: 1,
  },
  {
    id: "cc_only",
    display_name: "CC'd, never participated",
    description: "Threads where you were CC'd but never replied, older than 60 days",
    priority: 7,
    default_action: "archive",
    enabled: 1,
  },
  {
    id: "large_attachments",
    display_name: "Large attachments",
    description: "Emails with attachments over 1 MB older than 12 months",
    priority: 8,
    default_action: "archive",
    enabled: 1,
  },
  {
    id: "one_off",
    display_name: "One-off senders",
    description: "Senders with ≤2 messages total, all unread, older than 90 days",
    priority: 9,
    default_action: "trash",
    enabled: 1,
  },
  {
    id: "high_volume_unread",
    display_name: "High-volume & mostly unread",
    description: "Senders with high monthly volume and >80% unread rate",
    priority: 10,
    default_action: "trash",
    enabled: 1,
  },
];

export const ALERT_DOMAINS = new Set([
  "github.com",
  "github.io",
  "sentry.io",
  "pagerduty.com",
  "datadoghq.com",
  "opsgenie.com",
  "circleci.com",
  "travis-ci.com",
  "travis-ci.org",
  "heroku.com",
  "sendgrid.net",
  "jenkins.io",
  "atlassian.net",
  "jira.com",
  "bitbucket.org",
  "gitlab.com",
  "newrelic.com",
  "pingdom.com",
  "statuspage.io",
  "cloudflare.com",
  "awsnotifications.com",
  "amazonaws.com",
  "vercel.com",
  "netlify.com",
]);

export const SOCIAL_DOMAINS = new Set([
  "linkedin.com",
  "facebookmail.com",
  "facebook.com",
  "twitter.com",
  "x.com",
  "instagram.com",
  "reddit.com",
  "tiktok.com",
  "pinterest.com",
  "tumblr.com",
  "snapchat.com",
  "quora.com",
  "medium.com",
  "substack.com",
]);

export const RECEIPT_DOMAINS = new Set([
  "amazon.com",
  "amazon.co.uk",
  "amazon.de",
  "amazon.fr",
  "amazon.es",
  "amazon.it",
  "amazon.ca",
  "amazon.com.au",
  "amazon.co.jp",
  "ebay.com",
  "paypal.com",
  "stripe.com",
  "shopify.com",
  "etsy.com",
  "walmart.com",
  "target.com",
  "bestbuy.com",
  "uber.com",
  "ubereats.com",
  "doordash.com",
  "grubhub.com",
  "lyft.com",
  "airbnb.com",
  "booking.com",
  "expedia.com",
  "apple.com",
  "google.com",
  "microsoft.com",
  "netflix.com",
  "spotify.com",
  "hulu.com",
  "disneyplus.com",
]);

export const RECEIPT_SUBJECT_PATTERNS = [
  /order\s*(confirmation|receipt|shipped|delivered)/i,
  /your\s*(order|purchase|receipt|invoice)/i,
  /receipt\s*(for|from)/i,
  /invoice\s*(from|#)/i,
  /payment\s*(received|confirmation|receipt)/i,
  /subscription\s*(renewed|renewal|receipt)/i,
  /booking\s*confirmation/i,
  /reservation\s*confirmation/i,
];

export const PROMO_SUBJECT_PATTERNS = [
  /\d+%\s*off/i,
  /\$\d+\s*off/i,
  /sale|deal|offer|discount|coupon|promo|savings/i,
  /expires?\s*(soon|today|tomorrow)/i,
  /limited\s*time/i,
  /last\s*chance/i,
  /don't\s*miss/i,
  /exclusive\s*(offer|deal|access)/i,
  /flash\s*sale/i,
  /clearance/i,
  /free\s*shipping/i,
];
